# This is a basic workflow to help you get started with Actions
# 抄艾佬的作品https://github.com/HighCWu/onnxruntime

name: 编译cocotools在Windows下的Whl包

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # 此处将涉及编译后whl适用的平台
    runs-on: windows-2019
    
    strategy:
      matrix:
        python-version: [ '3.6', '3.7', '3.8', '3.9' ]
    name: Python环境为 ${{ matrix.python-version }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

#       - name: Install VS 2019
#         run: |
#           choco install visualstudio2019community
#           choco install visualstudio2019-workload-nativedesktop
          
#       - name: Get specific version CMake, v3.18.4
#         run: choco install cmake --version=3.18.4

      # Build Ort DML Wheel for Python
      - name: 正在编译 ${{ matrix.python-version }} 的Whl文件
        run: |
          # 填写需要编译Whl包的Git仓库，此处以QPT为例
          git clone https://github.com/cocodataset/cocoapi
          cd cocoapi/PythonAPI
          python -m pip install -U setuptools wheel
          python setup.py sdist bdist_wheel
        
      - name: 上传文件
        uses: actions/upload-artifact@v2
        with: 
          name: Whl-${{ matrix.python-version }}
          path: cocoapi/PythonAPI
